CREATE TABLE [MEDICO].[MEDICO]
(
[CODMED] [int] NOT NULL IDENTITY(1, 1),
[NOMMED] [varchar] (120) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPATMED] [varchar] (120) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEMATMED] [varchar] (120) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECNACMED] [date] NOT NULL,
[SEXMED] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIMED] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFMED] [varchar] (9) COLLATE Modern_Spanish_CI_AS NULL,
[EMAILMED] [varchar] (120) COLLATE Modern_Spanish_CI_AS NULL,
[DOMMED] [varchar] (120) COLLATE Modern_Spanish_CI_AS NULL,
[UBIGEOMED] [char] (6) COLLATE Modern_Spanish_CI_AS NULL,
[FECREGMED] [datetime] NOT NULL CONSTRAINT [DF__MEDICO__FECREGME__45F365D3] DEFAULT (getdate()),
[OBSERVMED] [varchar] (1800) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [MEDICO].[MEDICO] ADD CONSTRAINT [PK_CODMED] PRIMARY KEY CLUSTERED  ([CODMED]) ON [PRIMARY]
GO
ALTER TABLE [MEDICO].[MEDICO] ADD CONSTRAINT [FK_MEDICO_UBIGEO] FOREIGN KEY ([UBIGEOMED]) REFERENCES [PACIENTE].[UBIGEO] ([CODUB])
GO
