CREATE TABLE [PACIENTE].[PACIENTE]
(
[CODPAC] [int] NOT NULL IDENTITY(1, 1),
[NOMPAC] [varchar] (120) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPATPAC] [varchar] (120) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEMATPAC] [varchar] (120) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECNACPAC] [date] NOT NULL,
[SEXPAC] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIPAC] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFPAC] [varchar] (9) COLLATE Modern_Spanish_CI_AS NULL,
[EMAILPAC] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DOMPAC] [varchar] (120) COLLATE Modern_Spanish_CI_AS NULL,
[UBIGEOPAC] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECREGPAC] [datetime] NOT NULL CONSTRAINT [DF__PACIENTE__FECREG__37A5467C] DEFAULT (getdate()),
[OBSERVPAC] [varchar] (250) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[PACIENTE] ADD CONSTRAINT [PK_CODPAC] PRIMARY KEY CLUSTERED  ([CODPAC]) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[PACIENTE] ADD CONSTRAINT [FK_PACIENTE_UBIGEO] FOREIGN KEY ([UBIGEOPAC]) REFERENCES [PACIENTE].[UBIGEO] ([CODUB])
GO
