CREATE TABLE [PACIENTE].[HISTORIA_PACIENTE]
(
[CODHIST] [int] NOT NULL,
[CODPAC] [int] NOT NULL,
[CODMED] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[HISTORIA_PACIENTE] ADD CONSTRAINT [PK_CODHIST] PRIMARY KEY CLUSTERED  ([CODHIST], [CODPAC], [CODMED]) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[HISTORIA_PACIENTE] ADD CONSTRAINT [FK_HISTORIA_PACIENTE_HISTORIA] FOREIGN KEY ([CODHIST]) REFERENCES [HISTORIA].[HISTORIA] ([CODHIST])
GO
ALTER TABLE [PACIENTE].[HISTORIA_PACIENTE] ADD CONSTRAINT [FK_HISTORIA_PACIENTE_MEDICO] FOREIGN KEY ([CODMED]) REFERENCES [MEDICO].[MEDICO] ([CODMED])
GO
ALTER TABLE [PACIENTE].[HISTORIA_PACIENTE] ADD CONSTRAINT [FK_HISTORIA_PACIENTE_PACIENTE] FOREIGN KEY ([CODPAC]) REFERENCES [PACIENTE].[PACIENTE] ([CODPAC])
GO
