CREATE TABLE [PACIENTE].[TURNO_PACIENTE]
(
[CODTUR] [int] NOT NULL,
[CODPAC] [int] NOT NULL,
[CODMED] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[TURNO_PACIENTE] ADD CONSTRAINT [PK_CODTUR] PRIMARY KEY CLUSTERED  ([CODTUR], [CODPAC], [CODMED]) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[TURNO_PACIENTE] ADD CONSTRAINT [FK_TURNO_PACIENTE_MEDICO] FOREIGN KEY ([CODMED]) REFERENCES [MEDICO].[MEDICO] ([CODMED])
GO
ALTER TABLE [PACIENTE].[TURNO_PACIENTE] ADD CONSTRAINT [FK_TURNO_PACIENTE_PACIENTE] FOREIGN KEY ([CODPAC]) REFERENCES [PACIENTE].[PACIENTE] ([CODPAC])
GO
ALTER TABLE [PACIENTE].[TURNO_PACIENTE] ADD CONSTRAINT [FK_TURNO_PACIENTE_TURNO] FOREIGN KEY ([CODTUR]) REFERENCES [HISTORIA].[TURNO] ([CODTUR])
GO
